### ISSUE TITLE
Update wiki for v0.4.0 release

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#60]
**Todo**
  - [x] Update & test install from source instructions for Linux, MacOS (Windows is forthcoming) 
  - Update user guide
    - Basic Workflow
      - [x] Make new video walkthrough Pupil Capture bundle
      - [x] Make new video walkthrough for Pupil Player bundle
      - [x] Revise notes in all sections 
    - Pupil Capture
      - [x] Update screenshots
    - Pupil Player
      - [x] Update screenshots
      - [x] Document existing plugins
    - Data format
      - [x] Update data format specifications based on revisions made in v0.4.0
  - Update developer guide ... lots of revisions to be done here (perhaps list below in comments)

**Comment by willpatera** [comment]
:heavy_check_mark: - Tested install instructions on Ubuntu 14.04 -- working.

**Comment by mkassner** [comment]
Tested on 10.9 and 10.10 from source - working

**Comment by mkassner** [comment]
Tested  Capture bundle on 10.9 and 10.10 - working

**Comment by mkassner** [comment]
Player bundle works on 10.8 and 10.9 fails with crash in libgl.dylib on 10.10

**Comment by cpicanco** [comment]
Tested install instructions on Lubuntu 14.04.02 LTS -- working:

 - after fixing  broken head repositories #75, #82;
- installing a dependency for av #81;
- and after @mkassner add some new dependencies (libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev).

**Comment by willpatera** [comment]
Added new videos for Pupil Capture -- eye settings, calibration, and recording -- to the [Basic Workflow](https://github.com/pupil-labs/pupil/wiki/Basic-Workflow). Todo: add captions for screen based calibration workflow and recording. The intention is for each video to be very concise so that we can easily update/replace in the future when the interface changes or new features are added.

**Comment by willpatera** [comment]
Updated screenshots for [Pupil Player](https://github.com/pupil-labs/pupil/wiki/Pupil-Player) and added documentation on current plugins available in Pupil Player in the user guide. Also updated the TOC in the user guide.

**Comment by willpatera** [comment]
I will close this issue for now, but developer notes could still use a more documentation.
